### ISSUE TITLE
webpack 使用过程中的坑

### ISSUE THREAD

**Issue by hoperyy** [hoperyy/deep-webpack#3]
+   `extract-text-webpack-plugin`

    `extract-text-webpack-plugin` 如果将 css 文件单独抽离出来，不会有 HMR（hot module reload）的效果，因此在开发环境下，不能使用这个插件，只在生产环境下使用
    
+   `webpack-dev-server`

    错误信息：`Can't resolve 'fs' in webpack-dev-server/client`
    
    如果 `webpack` 配置中有 `resolve.mainFields`，但是没有包含以下三个配置：`["browser", "module", "main"]`，在使用 `webpack-dev-server` 的时候就会报错。
    
    解决方案：删除 `resolve.mainFields` 或将其配置的值至少有 `["browser", "module", "main"]`
    
    issue：https://github.com/webpack/webpack-dev-server/issues/727

+  如何支持 `module.exports` 和 `import` 混用：https://github.com/59naga/babel-plugin-add-module-exports

    通常情况下是不建议混用的，但在特殊的场景下，比如历史包袱等，可以用这个方案处理

**Comment by VinceFanZ** [comment]
你有遇到这个问题么，打包没有错，运行就。。。
<img width="993" alt="2017-07-18 12 33 27" src="https://user-images.githubusercontent.com/7631809/28300941-7bdc9eb8-6bb5-11e7-9cb6-d8aa8862ab4a.png">

**Comment by hoperyy** [comment]
还没遇到，不过感觉像是 `module.exports`、`export default`、`require`  混用导致的报错

这个 issue 应该有用：https://github.com/webpack/webpack/issues/4039

@VinceFanZ

**Comment by VinceFanZ** [comment]
解决了  把.babelrc 里 es2015中的"modules": false 去掉就好了，不过还是要 debug这个库的作者改掉

**Comment by hoperyy** [comment]
不错 @VinceFanZ
